on:
  pull_request:
    types: [opened, closed]

jobs:
  debug:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: print branch name
      - shell: bash
      - run: echo ${{github.head_ref}}
