on:
  pull_request:
    types: [opened, closed]

jobs:
  debug:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: Print branch name
        env:
          BRANCH_NAME: ${{github.head_ref}}
        run: echo $BRANCH_NAME
