on: 
  pull_request:
    types: closed

jobs:
  clean_S3:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Delete S3 Objects with branch-name prefix
        env: 
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          aws s3 rm s3://$S3_BUCKET/git/$BRANCH_NAME --quiet --recursive
