name: Upload files to S3
on: push
jobs:
  upload:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch

      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload files to S3 with branch-name prefix on push
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        run: | 
          aws s3 cp . s3://$S3_BUCKET/git/$BRANCH_NAME/ --recursive --exclude "*" --include "*.json" --include "*.xml"
