name: Amazon S3 Deleting Object

on:
  pull_request:
    types: closed

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Delete file from S3
        env: 
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          aws s3 rm s3://$S3_BUCKET/git/$BRANCH_NAME/sample.txt --quiet
